language: node_js # 编译语言、环境

sudo: required # 需要管理员权限

dist: xenial # 指定系统版本为 Ubuntu 16.04.6 LTS (Xenial Xerus)

node_js: stable # Node.js 版本

branches:
  only:
    - source # 只有 source 分支更改才触发 CI

before_install: 
  - export TZ='Asia/Shanghai' # 配置时区为 UTC+8
  - npm install hexo-cli # 安装 hexo

install:
  - npm install # 安装依赖

script:
  - hexo clean
  - hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public # 需要推送到 GitHub 的静态文件目录，Hexo 生成在 public 目录
  name: $GIT_NAME
  email: $GIT_EMAIL
  github_token: $GITHUB_TOKEN
  keep-history: true # 保持推送记录，以增量提交的方式
  target-branch: master
  on:
    branch: source
  